
FUNDS = [
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS NÃO-PADRONIZADOS CIELO",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS CIELO",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS CIELO EMISSORES II",
    "MOLEIRO CONSIGNADO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS DONEGAL",
    "FUNDO DE INVES TIMENTO EM DIREITOS CREDITORIOS FORTBRASIL",
    "RB CAPITAL CREDIT ALPHA STRATEGY I FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",
    "FIDC MRFG FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    
    "CREDITO UNIVERSITARIO II FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",
    "PAGEDU FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",  
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS LAR",
    "GUARDIAN MULTI CONSIGNADO III FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS UPL 02",
    "ESTRATÉGIA VINCULADA I FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA",
    "GONN FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",    
    "FARM TECH BRADESCO ASSET AGRO I FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    
    "FARMTECH UP CREDIT FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS TM II",
    "TALÓ 1 FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "SOTREQ FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA",
    
    "FARMTECH SYNGENTA FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "PÁTRIA INFRA CRÉDITO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS NUTRIEN I",
    "AURORA FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS NAO-PADRONIZADO",
    
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS BV - CRÉDITO DE VEÍCULOS",
    "MT INSS RECEIVABLES V FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS CONSIGNADOS",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS ASAAS II",
    "BEMOL CREDITO PESSOAL - FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",
    
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS SUMITOMO",
    "AUTOMOTIVO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "VÔNGOLE FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS NÃO-PADRONIZADOS",
    "CRÉDITO UNIVERSITÁRIO FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS",
    
    "CRÉDITO UNIVERSITÁRIO III FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - NÃO PADRONIZADO",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIOS SANTAFUSVE",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITORIÓS NÃO PADRONIZADOS - CONSÓRCIOS II",
    "FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS LIVERPOOL",
    
    "SAN Créditos Estruturados I Fundo de Investimento em Direitos Creditórios Não Padronizados",
    "CORTEVA AGRISCIENCE FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS I",
    "FARM TECH IBBA I FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "BRADESCO FARMTECH FUNDO DE INVESTIMENTO NAS CADEIAS PRODUTIVAS AGROINDUSTRIAIS FIAGRO - DC",
    "PNEUCASH FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS DE CLASSE ÚNICA FECHADA - RESP LTDA",
    
    "ESTRATÉGIA VINCULADA II FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS - RESPONSABILIDADE LIMITADA",
    "MAQNELSON FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "MCPO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS",
    "PÁTRIA CRÉDITO ESTRUTURADO FUNDO DE INVESTIMENTO EM DIREITOS CREDITÓRIOS"
]



